"use client";

import { AuthGoogleProvider } from "@/context/authGoogle";
import PreviewProvider from "@/context/preview";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthGoogleProvider>
          <PreviewProvider>
            <Toaster
              toastOptions={{
                position: "bottom-right",
                style: {
                  background: "#0b89af",
                  color: "#ffff",
                },
              }}
            />
            {/* <Header /> */}
            <main className="relative flex flex-col justify-between">
              {children}
            </main>
          </PreviewProvider>
        </AuthGoogleProvider>
      </body>
    </html>
  );
}
